name: dask-cse255
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab>=3
  - numpy>=1.24
  - pandas>=1.5
  - scipy>=1.10
  - dask>=2023.1
  - distributed>=2023.1
  - dask-labextension
  - bokeh>=2.4
  - matplotlib>=3.7
  - seaborn>=0.12
  - pyarrow>=12
  - s3fs>=2023.6
  - xarray>=2023.5
  - zarr
  - pooch
  - python-graphviz
  - ipycytoscape
  - scikit-learn>=1.3
  - tqdm>=4.64
  - pyproj
  - pip
  - pip:
      - pygam>=0.9.0

